name: Economy
version: '1.0-SNAPSHOT'
main: org.mariobj99dev.Economy.Main
api-version: '1.21'
commands:
  getcurrencies:
    description: "Obtiene información de todas las divisas."
    usage: "/getcurrencies"
    permission: "economyapi.getcurrencies"
  getbanks:
    description: "Obtiene información de todos los bancos."
    usage: "/getbanks"
    permission: "economyapi.getbanks"
  getbank:
    description: "Muestra información de un banco"
    usage: "/getbank <id>"
    permission: "economy.getbank"
  currency:
    description: "Gestiona las monedas del servidor"
    usage: "/currency <create | get | list | update | delete> [params]"
    permission: "economy.currency"